# Generated by Django 2.0 on 2017-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_customer',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
