# Generated by Django 2.0 on 2017-12-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171215_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_order',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
