# Generated by Django 2.0 on 2018-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180117_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
