# Generated by Django 2.0 on 2017-12-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
    ]
