# Generated by Django 2.0 on 2017-12-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171221_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='is_main',
        ),
    ]
