# Generated by Django 2.0 on 2017-12-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171223_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
